The following notebook is a modified version of the one found in https://github.com/openai/whisper/blob/main/notebooks/LibriSpeech.ipynb

In [ ]:
! pip install git+https://github.com/openai/whisper.git
! pip install jiwer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/openai/whisper.git to /tmp/pip-req-build-fqbaw39j
  Running command git clone -q https://github.com/openai/whisper.git /tmp/pip-req-build-fqbaw39j
     |████████████████████████████████| 5.8 MB 12.3 MB/s 
     |████████████████████████████████| 7.6 MB 41.9 MB/s 
     |████████████████████████████████| 182 kB 14.1 MB/s 
  Created wheel for whisper: filename=whisper-1.0-py3-none-any.whl size=1175327 sha256=85db21f9eeecf0d7b64b68375aaeead04fe2652ae25e2fda4bb98cefb77f85f5
  Stored in directory: /tmp/pip-ephem-wheel-cache-rhwltjyl/wheels/a7/70/18/b7693c07b1d18b3dafb328f5d0496aa0d41a9c09ef332fd8e6
Successfully built whisper
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.4 MB 30.4 MB/s 
     |████████████████████████████████| 2.2 MB 47.0 MB/s 


In [ ]:
!pip install evaluate

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 72 kB 1.6 MB/s 
     |████████████████████████████████| 451 kB 57.6 MB/s 
     |████████████████████████████████| 212 kB 73.7 MB/s 
     |████████████████████████████████| 132 kB 70.7 MB/s 
     |████████████████████████████████| 127 kB 78.1 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3


In [ ]:
!pip install rouge_score

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24955 sha256=c412297b13940b0f9e76d17e841693783e167862dd3e737d79ea50628d0eb3b0
  Stored in directory: /root/.cache/pip/wheels/24/55/6f/ebfc4cb176d1c9665da4e306e1705496206d08215c1acd9dde
Successfully built rouge-score


In [ ]:
import os
import numpy as np

try:
    import tensorflow  # required in Colab to avoid protobuf compatibility issues
except ImportError:
    pass

import torch
import pandas as pd
import whisper
import torchaudio
import evaluate

from tqdm.notebook import tqdm
from evaluate import load


DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
import pickle
from datasets import Audio
from datasets import Dataset
from datasets import Features

In [ ]:
# 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
#from huggingface_hub import notebook_login

#notebook_login()

In [ ]:
model = whisper.load_model("small")

100%|███████████████████████████████████████| 461M/461M [00:04<00:00, 97.2MiB/s]


In [ ]:
from datasets import load_dataset
from datasets import DownloadConfig
link = "DTU54DL/common-accent-augmented"
common_voice = load_dataset(link, download_config=DownloadConfig(delete_extracted=True))

Extracting data files #0:   0%|          | 0/1 [00:00<?, ?obj/s]

Extracting data files #1:   0%|          | 0/1 [00:00<?, ?obj/s]

Generating train split:   0%|          | 0/10000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/451 [00:00<?, ? examples/s]

Dataset parquet downloaded and prepared to /root/.cache/huggingface/datasets/DTU54DL___parquet/DTU54DL--common-accent-augmented-f271fe9aab49c35b/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
common_voice

DatasetDict({
    train: Dataset({
        features: ['audio', 'sentence', 'accent'],
        num_rows: 10000
    })
    test: Dataset({
        features: ['audio', 'sentence', 'accent'],
        num_rows: 451
    })
})

In [ ]:
audios=common_voice["test"]["audio"]
sentences = common_voice["test"]["sentence"]

In [ ]:
audios_array = [a["array"] for a in audios]
audios_array

[array([ 0.00012207,  0.00021362,  0.00015259, ...,  0.00067139,
        -0.00384521, -0.00650024]),
 array([-3.05175781e-05, -6.10351562e-05, -3.05175781e-05, ...,
         8.23974609e-03,  6.34765625e-03,  6.10351562e-03]),
 array([-0.00119019,  0.00189209,  0.00817871, ..., -0.00100708,
        -0.00222778, -0.00408936]),
 array([0.01385498, 0.0222168 , 0.02053833, ..., 0.02740479, 0.00927734,
        0.01925659]),
 array([-3.05175781e-05, -9.15527344e-05, -6.10351562e-05, ...,
         3.05175781e-05, -3.05175781e-05, -6.10351562e-05]),
 array([ 9.15527344e-05,  1.22070312e-04,  1.22070312e-04, ...,
        -2.83813477e-03, -1.25122070e-03,  1.03759766e-03]),
 array([-0.00021362, -0.00030518, -0.00027466, ...,  0.00393677,
         0.00488281,  0.00585938]),
 array([-3.05175781e-05, -3.05175781e-05, -3.05175781e-05, ...,
        -1.83105469e-04,  1.83105469e-04,  5.18798828e-04]),
 array([-3.05175781e-05, -6.10351562e-05, -3.05175781e-05, ...,
         7.93457031e-04,  4.78210449e-

In [ ]:
df = pd.DataFrame(data={"reference": sentences})
df

reference
0    The boy swore that, every time he heard the al...
1    Their faces were hidden behind blue veils, wit...
2     A scientist in a lab coat is using a microscope.
3         A friend to everybody is a friend to nobody.
4    A group of people, one of them with a guitar, ...
..                                                 ...
446               This plank was made for walking on .
447  She was beautiful from behind, but he couldn't...
448  A bus shuttle took us from the airport to the ...
449             It was the pure Language of the World.
450  The buttons made a strange clicking sound when...

[451 rows x 1 columns]

In [ ]:
#options = whisper.DecodingOptions()
options = whisper.DecodingOptions(language="en", fp16 = False, without_timestamps=True)

In [ ]:
audio=audios_array

In [ ]:
audio[1]

array([-3.05175781e-05, -6.10351562e-05, -3.05175781e-05, ...,
        8.23974609e-03,  6.34765625e-03,  6.10351562e-03])

In [ ]:

hypotheses = []
references = []
language= []
for i in range(0,450): 
  aud=whisper.pad_or_trim(audio[i])
  mel = whisper.log_mel_spectrogram(torch.tensor(aud,dtype=torch.float32)).to(model.device)
  _, probs = model.detect_language(mel)
  #print(f"Detected language: {max(probs, key=probs.get)}")
  language.append(max(probs, key=probs.get))
  result = whisper.decode(model, mel, options)
  hypotheses.append(result.text)
  references.append(df['reference'][i])

In [ ]:
#hypothesis = []
#for i in range(0,len(hypotheses)):
#    print(hypotheses[i].text)
#    hypothesis.append(hypotheses[i].text)

In [ ]:
len(language)

450


calculating non english inference

In [ ]:
data = pd.DataFrame(dict(hypothesis=hypotheses, reference=references))
data

hypothesis  \
0    The boy swore that, every time he heard the al...   
1    Their faces were hidden behind blue veils with...   
2     A scientist in a lab coat is using a microscope.   
3         A friend to everybody is a friend to nobody.   
4    A group of people were loved by the guitar gir...   
..                                                 ...   
445           But as time passed, time to have change.   
446                This plank was made for walking on.   
447  She was beautiful from behind but he couldn't ...   
448  Our bus shuttle took us from the airport to th...   
449               It was the pure langos of the world.   

                                             reference  
0    The boy swore that, every time he heard the al...  
1    Their faces were hidden behind blue veils, wit...  
2     A scientist in a lab coat is using a microscope.  
3         A friend to everybody is a friend to nobody.  
4    A group of people, one of them with a guitar, ...  
..                                                 ...  
445          But, as time passed, Tangier had changed.  
446               This plank was made for walking on .  
447  She was beautiful from behind, but he couldn't...  
448  A bus shuttle took us from the airport to the ...  
449             It was the pure Language of the World.  

[450 rows x 2 columns]

In [ ]:
import jiwer
from whisper.normalizers import EnglishTextNormalizer

normalizer = EnglishTextNormalizer()

In [ ]:
data["hypothesis_clean"] = [normalizer(text) for text in data["hypothesis"]]
data["reference_clean"] = [normalizer(text) for text in data["reference"]]
data

hypothesis  \
0    The boy swore that, every time he heard the al...   
1    Their faces were hidden behind blue veils with...   
2     A scientist in a lab coat is using a microscope.   
3         A friend to everybody is a friend to nobody.   
4    A group of people were loved by the guitar gir...   
..                                                 ...   
445           But as time passed, time to have change.   
446                This plank was made for walking on.   
447  She was beautiful from behind but he couldn't ...   
448  Our bus shuttle took us from the airport to th...   
449               It was the pure langos of the world.   

                                             reference  \
0    The boy swore that, every time he heard the al...   
1    Their faces were hidden behind blue veils, wit...   
2     A scientist in a lab coat is using a microscope.   
3         A friend to everybody is a friend to nobody.   
4    A group of people, one of them with a guitar, ...   
..                                                 ...   
445          But, as time passed, Tangier had changed.   
446               This plank was made for walking on .   
447  She was beautiful from behind, but he couldn't...   
448  A bus shuttle took us from the airport to the ...   
449             It was the pure Language of the World.   

                                      hypothesis_clean  \
0    the boy swore that every time he heard the ala...   
1    their faces were hidden behind blue veils with...   
2      a scientist in a lab coat is using a microscope   
3          a friend to everybody is a friend to nobody   
4    a group of people were loved by the guitar gir...   
..                                                 ...   
445             but as time passed time to have change   
446                 this plank was made for walking on   
447  she was beautiful from behind but he could not...   
448  our bus shuttle took us from the airport to th...   
449                it was the pure langos of the world   

                                       reference_clean  
0    the boy swore that every time he heard the ala...  
1    their faces were hidden behind blue veils with...  
2      a scientist in a lab coat is using a microscope  
3          a friend to everybody is a friend to nobody  
4    a group of people one of them with a guitar we...  
..                                                 ...  
445             but as time passed tangier had changed  
446                 this plank was made for walking on  
447  she was beautiful from behind but he could not...  
448  a bus shuttle took us from the airport to the ...  
449              it was the pure language of the world  

[450 rows x 4 columns]

In [ ]:
non_english=((len(language) - language.count('en')) / len(language))
print(f"Non English ratio: {non_english * 100:.2f} %")

wer = jiwer.wer(list(data["reference_clean"]), list(data["hypothesis_clean"]))

print(f"WER: {wer * 100:.2f} %")

Non English ratio: 11.56 %
WER: 23.67 %


In [ ]:
def bleu_eval(predictions,references):
  bleu = evaluate.load("bleu")
  results = bleu.compute(predictions=predictions, references=references)
  print(results)
def rouge_eval(predictions,references):
  rouge = evaluate.load("rouge")
  results = rouge.compute(predictions=predictions, references=references)
  print(results)

In [ ]:
bleu_eval(predictions=data["hypothesis_clean"], references=data["reference_clean"])

{'bleu': 0.6570389943350469, 'precisions': [0.7898762654668167, 0.690863579474343, 0.6161217587373168, 0.5543022881082823], 'brevity_penalty': 1.0, 'length_ratio': 1.0263218656199493, 'translation_length': 4445, 'reference_length': 4331}


In [ ]:
rouge_eval(predictions=data["hypothesis_clean"], references=data["reference_clean"])

{'rouge1': 0.794237524316342, 'rouge2': 0.6943877338741427, 'rougeL': 0.7928598082290929, 'rougeLsum': 0.7935131080447032}


In [ ]:
non_english = []
for i in range(0,len(language)):
  if language[i]!='en':
    non_english.append(i)

import csv

with open('tutorial.csv', 'w', newline='') as csvfile:
    
    # include the names for each column/feature
    #fieldnames = ['number','colour']
    fields=['indexes']

    # create a writer object that takes the csv file and fieldnames as parameters.
    thewriter = csv.DictWriter(csvfile, fieldnames=fields)
    
    # this writer the fieldnames to the file, i.e 'number' and 'colour'
    thewriter.writeheader()
    
    for index in non_english:
        thewriter.writerow({'indexes':index})

In [ ]:
non_english

[2,
 4,
 8,
 25,
 34,
 42,
 45,
 49,
 55,
 59,
 83,
 88,
 95,
 118,
 129,
 139,
 156,
 165,
 166,
 170,
 189,
 192,
 196,
 199,
 201,
 204,
 205,
 239,
 251,
 253,
 261,
 272,
 275,
 277,
 281,
 283,
 293,
 305,
 319,
 321,
 337,
 340,
 347,
 366,
 376,
 379,
 411,
 421,
 426,
 428,
 434,
 435]