The following notebook is a modified version of the one found in https://github.com/openai/whisper/blob/main/notebooks/LibriSpeech.ipynb

In [ ]:
! pip install git+https://github.com/openai/whisper.git
! pip install jiwer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/openai/whisper.git to /tmp/pip-req-build-civrotdx
  Running command git clone -q https://github.com/openai/whisper.git /tmp/pip-req-build-civrotdx
     |████████████████████████████████| 5.8 MB 19.7 MB/s 
     |████████████████████████████████| 7.6 MB 49.1 MB/s 
     |████████████████████████████████| 182 kB 30.0 MB/s 
  Created wheel for whisper: filename=whisper-1.0-py3-none-any.whl size=1175239 sha256=5772a62b1429f87e3e32df6b67abfdc8c108deda40d9468010489ff879fa1d31
  Stored in directory: /tmp/pip-ephem-wheel-cache-r4hyj_72/wheels/a7/70/18/b7693c07b1d18b3dafb328f5d0496aa0d41a9c09ef332fd8e6
Successfully built whisper
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.4 MB 47.2 MB/s 
     |████████████████████████████████| 2.2 MB 58.0 MB/s 


In [ ]:
!pip install evaluate

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 72 kB 1.4 MB/s 
     |████████████████████████████████| 451 kB 55.6 MB/s 
     |████████████████████████████████| 212 kB 55.2 MB/s 
     |████████████████████████████████| 132 kB 66.2 MB/s 
     |████████████████████████████████| 127 kB 57.8 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3


In [ ]:
!pip install rouge_score

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24955 sha256=55896b7ee2bf734b8d900eb1db044b9ef73ef4a10d13b331d93d404dd3b021b4
  Stored in directory: /root/.cache/pip/wheels/24/55/6f/ebfc4cb176d1c9665da4e306e1705496206d08215c1acd9dde
Successfully built rouge-score


In [ ]:
import os
import numpy as np

try:
    import tensorflow  # required in Colab to avoid protobuf compatibility issues
except ImportError:
    pass

import torch
import pandas as pd
import whisper
import torchaudio
import evaluate

from tqdm.notebook import tqdm
from evaluate import load


DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
import pickle
from datasets import Audio
from datasets import Dataset
from datasets import Features

In [ ]:
# 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
#from huggingface_hub import notebook_login

#notebook_login()

In [ ]:
model = whisper.load_model("small")

100%|███████████████████████████████████████| 461M/461M [00:10<00:00, 47.4MiB/s]


In [ ]:
from datasets import load_dataset
from datasets import DownloadConfig
link = "DTU54DL/libri_augmented_test_set"
common_voice = load_dataset(link, download_config=DownloadConfig(delete_extracted=True))

Extracting data files:   0%|          | 0/1 [00:00<?, ?it/s]

Generating test split:   0%|          | 0/2620 [00:00<?, ? examples/s]

Dataset parquet downloaded and prepared to /root/.cache/huggingface/datasets/DTU54DL___parquet/DTU54DL--libri_augmented_test_set-5bba61664eb554b8/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec. Subsequent calls will reuse this data.


  0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
common_voice

DatasetDict({
    test: Dataset({
        features: ['file', 'audio', 'text', 'speaker_id', 'chapter_id', 'id'],
        num_rows: 2620
    })
})

In [ ]:
audios=common_voice["test"]["audio"]
sentences = common_voice["test"]["text"]

In [ ]:
audios_array = [a["array"] for a in audios]
audios_array

[array([-0.00048828,  0.00140381,  0.01065063, ..., -0.03793335,
        -0.15005493, -0.1428833 ]),
 array([-0.02124023, -0.0272522 ,  0.01904297, ...,  0.01419067,
         0.00500488, -0.00280762]),
 array([0.00408936, 0.00497437, 0.00469971, ..., 0.11419678, 0.06451416,
        0.08990479]),
 array([ 0.00500488, -0.00430298, -0.00228882, ...,  0.02044678,
         0.00595093, -0.02005005]),
 array([-0.03277588, -0.00747681,  0.01916504, ...,  0.01205444,
        -0.02114868, -0.02880859]),
 array([ 0.00714111, -0.07748413, -0.20205688, ...,  0.13925171,
         0.1652832 ,  0.16766357]),
 array([-0.05059814, -0.05612183, -0.0005188 , ..., -0.12191772,
        -0.00808716,  0.10705566]),
 array([-0.07849121,  0.04049683,  0.13531494, ...,  0.00546265,
        -0.06072998, -0.10458374]),
 array([-0.00024414,  0.00106812, -0.00042725, ..., -0.01263428,
        -0.01077271, -0.00756836]),
 array([ 3.05175781e-05, -3.05175781e-05,  1.25122070e-03, ...,
         1.95312500e-03,  2.74658

In [ ]:
df = pd.DataFrame(data={"reference": sentences})
df

reference
0        CONCORD RETURNED TO ITS PLACE AMIDST THE TENTS
1     THE ENGLISH FORWARDED TO THE FRENCH BASKETS OF...
2     CONGRATULATIONS WERE POURED IN UPON THE PRINCE...
3     FROM THE RESPECT PAID HER ON ALL SIDES SHE SEE...
4     SHE TAUGHT HER DAUGHTER THEN BY HER OWN AFFECT...
...                                                 ...
2615  THOSE PRETTY WRONGS THAT LIBERTY COMMITS WHEN ...
2616                                              AY ME
2617  NO MATTER THEN ALTHOUGH MY FOOT DID STAND UPON...
2618  THOUGHT KILLS ME THAT I AM NOT THOUGHT TO LEAP...
2619  MY HEART DOTH PLEAD THAT THOU IN HIM DOST LIE ...

[2620 rows x 1 columns]

In [ ]:
options = whisper.DecodingOptions()

In [ ]:
audio=audios_array

In [ ]:
audio[1]

array([-0.02124023, -0.0272522 ,  0.01904297, ...,  0.01419067,
        0.00500488, -0.00280762])

In [ ]:

hypotheses = []
references = []
language= []
for i in range(0,2619): 
  aud=whisper.pad_or_trim(audio[i])
  mel = whisper.log_mel_spectrogram(torch.tensor(aud,dtype=torch.float32)).to(model.device)
  _, probs = model.detect_language(mel)
  #print(f"Detected language: {max(probs, key=probs.get)}")
  language.append(max(probs, key=probs.get))
  result = whisper.decode(model, mel, options)
  hypotheses.append(result.text)
  references.append(df['reference'][i])

In [ ]:
#hypothesis = []
#for i in range(0,len(hypotheses)):
#    print(hypotheses[i].text)
#    hypothesis.append(hypotheses[i].text)

In [ ]:
len(language)

2619


calculating non english inference

In [ ]:
data = pd.DataFrame(dict(hypothesis=hypotheses, reference=references))
data

hypothesis  \
0      Concorde returned to its place amidst the tents.   
1     The English voted to the French baskets of flo...   
2     Congratulations were poured in upon the Prince...   
3     From the respect paid her on all sides, she se...   
4     She taught her daughter, then, by her own affe...   
...                                                 ...   
2614  But was that all her reward? One of the ladies...   
2615  Those pretty wrongs that liberty commits, When...   
2616                                               I ME   
2617  No matter then, although my foot did stand, Up...   
2618  Thought kills me than I am not thought, to lea...   

                                              reference  
0        CONCORD RETURNED TO ITS PLACE AMIDST THE TENTS  
1     THE ENGLISH FORWARDED TO THE FRENCH BASKETS OF...  
2     CONGRATULATIONS WERE POURED IN UPON THE PRINCE...  
3     FROM THE RESPECT PAID HER ON ALL SIDES SHE SEE...  
4     SHE TAUGHT HER DAUGHTER THEN BY HER OWN AFFECT...  
...                                                 ...  
2614  BUT WAS THAT ALL HER REWARD ONE OF THE LADIES ...  
2615  THOSE PRETTY WRONGS THAT LIBERTY COMMITS WHEN ...  
2616                                              AY ME  
2617  NO MATTER THEN ALTHOUGH MY FOOT DID STAND UPON...  
2618  THOUGHT KILLS ME THAT I AM NOT THOUGHT TO LEAP...  

[2619 rows x 2 columns]

In [ ]:
import jiwer
from whisper.normalizers import EnglishTextNormalizer

normalizer = EnglishTextNormalizer()

In [ ]:
data["hypothesis_clean"] = [normalizer(text) for text in data["hypothesis"]]
data["reference_clean"] = [normalizer(text) for text in data["reference"]]
data

hypothesis  \
0      Concorde returned to its place amidst the tents.   
1     The English voted to the French baskets of flo...   
2     Congratulations were poured in upon the Prince...   
3     From the respect paid her on all sides, she se...   
4     She taught her daughter, then, by her own affe...   
...                                                 ...   
2614  But was that all her reward? One of the ladies...   
2615  Those pretty wrongs that liberty commits, When...   
2616                                               I ME   
2617  No matter then, although my foot did stand, Up...   
2618  Thought kills me than I am not thought, to lea...   

                                              reference  \
0        CONCORD RETURNED TO ITS PLACE AMIDST THE TENTS   
1     THE ENGLISH FORWARDED TO THE FRENCH BASKETS OF...   
2     CONGRATULATIONS WERE POURED IN UPON THE PRINCE...   
3     FROM THE RESPECT PAID HER ON ALL SIDES SHE SEE...   
4     SHE TAUGHT HER DAUGHTER THEN BY HER OWN AFFECT...   
...                                                 ...   
2614  BUT WAS THAT ALL HER REWARD ONE OF THE LADIES ...   
2615  THOSE PRETTY WRONGS THAT LIBERTY COMMITS WHEN ...   
2616                                              AY ME   
2617  NO MATTER THEN ALTHOUGH MY FOOT DID STAND UPON...   
2618  THOUGHT KILLS ME THAT I AM NOT THOUGHT TO LEAP...   

                                       hypothesis_clean  \
0       concorde returned to its place amidst the tents   
1     the english voted to the french baskets of flo...   
2     congratulations were poured in upon the prince...   
3     from the respect paid her on all sides she see...   
4     she taught her daughter then by her own affect...   
...                                                 ...   
2614  but was that all her reward one of the ladies ...   
2615  those pretty wrongs that liberty commits when ...   
2616                                               i me   
2617  no matter then although my foot did stand upon...   
2618  thought kills me than i am not thought to leap...   

                                        reference_clean  
0        concord returned to its place amidst the tents  
1     the english forwarded to the french baskets of...  
2     congratulations were poured in upon the prince...  
3     from the respect paid her on all sides she see...  
4     she taught her daughter then by her own affect...  
...                                                 ...  
2614  but was that all her reward one of the ladies ...  
2615  those pretty wrongs that liberty commits when ...  
2616                                              ay me  
2617  no matter then although my foot did stand upon...  
2618  thought kills me that i am not thought to leap...  

[2619 rows x 4 columns]

In [ ]:
non_english=((len(language) - language.count('en')) / len(language))
print(f"Non English ratio: {non_english * 100:.2f} %")

wer = jiwer.wer(list(data["reference_clean"]), list(data["hypothesis_clean"]))

print(f"WER: {wer * 100:.2f} %")

Non English ratio: 0.08 %
WER: 4.49 %


In [ ]:
def bleu_eval(predictions,references):
  bleu = evaluate.load("bleu")
  results = bleu.compute(predictions=predictions, references=references)
  print(results)
def rouge_eval(predictions,references):
  rouge = evaluate.load("rouge")
  results = rouge.compute(predictions=predictions, references=references)
  print(results)

In [ ]:
bleu_eval(predictions=data["hypothesis_clean"], references=data["reference_clean"])

{'bleu': 0.9208021674441338, 'precisions': [0.962010962010962, 0.9343222445367958, 0.9092606187729418, 0.885501941209096], 'brevity_penalty': 0.9983381806902009, 'length_ratio': 0.9983395599833956, 'translation_length': 52910, 'reference_length': 52998}


In [ ]:
rouge_eval(predictions=data["hypothesis_clean"], references=data["reference_clean"])

{'rouge1': 0.9535333876239944, 'rouge2': 0.9199705105454621, 'rougeL': 0.9533133128045423, 'rougeLsum': 0.9534158006571903}
