The following notebook is a modified version of the one found in https://github.com/openai/whisper/blob/main/notebooks/LibriSpeech.ipynb

In [ ]:
! pip install git+https://github.com/openai/whisper.git
! pip install jiwer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/openai/whisper.git to /tmp/pip-req-build-58z7epcu
  Running command git clone -q https://github.com/openai/whisper.git /tmp/pip-req-build-58z7epcu
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install evaluate

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install rouge_score

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import os
import numpy as np

try:
    import tensorflow  # required in Colab to avoid protobuf compatibility issues
except ImportError:
    pass

import torch
import pandas as pd
import whisper
import torchaudio
import evaluate

from tqdm.notebook import tqdm
from evaluate import load


DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
import pickle
from datasets import Audio
from datasets import Dataset
from datasets import Features

In [ ]:
# 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
#from huggingface_hub import notebook_login

#notebook_login()

In [ ]:
model = whisper.load_model("tiny")

In [ ]:
from datasets import load_dataset
from datasets import DownloadConfig
link = "DTU54DL/common-accent-augmented"
common_voice = load_dataset(link, download_config=DownloadConfig(delete_extracted=True))

  0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
common_voice

DatasetDict({
    train: Dataset({
        features: ['audio', 'sentence', 'accent'],
        num_rows: 10000
    })
    test: Dataset({
        features: ['audio', 'sentence', 'accent'],
        num_rows: 451
    })
})

In [ ]:
audios=common_voice["test"]["audio"]
sentences = common_voice["test"]["sentence"]

In [ ]:
audios_array = [a["array"] for a in audios]
audios_array

[array([ 0.00012207,  0.00021362,  0.00015259, ...,  0.00067139,
        -0.00384521, -0.00650024]),
 array([-3.05175781e-05, -6.10351562e-05, -3.05175781e-05, ...,
         8.23974609e-03,  6.34765625e-03,  6.10351562e-03]),
 array([-0.00119019,  0.00189209,  0.00817871, ..., -0.00100708,
        -0.00222778, -0.00408936]),
 array([0.01385498, 0.0222168 , 0.02053833, ..., 0.02740479, 0.00927734,
        0.01925659]),
 array([-3.05175781e-05, -9.15527344e-05, -6.10351562e-05, ...,
         3.05175781e-05, -3.05175781e-05, -6.10351562e-05]),
 array([ 9.15527344e-05,  1.22070312e-04,  1.22070312e-04, ...,
        -2.83813477e-03, -1.25122070e-03,  1.03759766e-03]),
 array([-0.00021362, -0.00030518, -0.00027466, ...,  0.00393677,
         0.00488281,  0.00585938]),
 array([-3.05175781e-05, -3.05175781e-05, -3.05175781e-05, ...,
        -1.83105469e-04,  1.83105469e-04,  5.18798828e-04]),
 array([-3.05175781e-05, -6.10351562e-05, -3.05175781e-05, ...,
         7.93457031e-04,  4.78210449e-

In [ ]:
df = pd.DataFrame(data={"reference": sentences})
df

reference
0    The boy swore that, every time he heard the al...
1    Their faces were hidden behind blue veils, wit...
2     A scientist in a lab coat is using a microscope.
3         A friend to everybody is a friend to nobody.
4    A group of people, one of them with a guitar, ...
..                                                 ...
446               This plank was made for walking on .
447  She was beautiful from behind, but he couldn't...
448  A bus shuttle took us from the airport to the ...
449             It was the pure Language of the World.
450  The buttons made a strange clicking sound when...

[451 rows x 1 columns]

In [ ]:
#options = whisper.DecodingOptions()
options = whisper.DecodingOptions(language="en", fp16 = False, without_timestamps=True)

In [ ]:
audio=audios_array

In [ ]:
audio[1]

array([-3.05175781e-05, -6.10351562e-05, -3.05175781e-05, ...,
        8.23974609e-03,  6.34765625e-03,  6.10351562e-03])

In [ ]:

hypotheses = []
references = []
language= []
for i in range(0,450): 
  aud=whisper.pad_or_trim(audio[i])
  mel = whisper.log_mel_spectrogram(torch.tensor(aud,dtype=torch.float32)).to(model.device)
  _, probs = model.detect_language(mel)
  #print(f"Detected language: {max(probs, key=probs.get)}")
  language.append(max(probs, key=probs.get))
  result = whisper.decode(model, mel, options)
  hypotheses.append(result.text)
  references.append(df['reference'][i])

In [ ]:
#hypothesis = []
#for i in range(0,len(hypotheses)):
#    print(hypotheses[i].text)
#    hypothesis.append(hypotheses[i].text)

In [ ]:
len(language)

450


calculating non english inference

In [ ]:
data = pd.DataFrame(dict(hypothesis=hypotheses, reference=references))
data

hypothesis  \
0    The boy saw that every time he hit the alarm h...   
1    The faces were hidden behind blue veils with o...   
2        A scientist in the lab is using a microscope.   
3         A friend to everybody is a friend to nobody.   
4    A group of who could learn from them with a gu...   
..                                                 ...   
445           But as time passed, channel has changed.   
446                 This plan was made for working on.   
447  She was beautiful from behind but he couldn't ...   
448  Now, buzz, shadow, to pass from the airport to...   
449             It was the pure language of the world.   

                                             reference  
0    The boy swore that, every time he heard the al...  
1    Their faces were hidden behind blue veils, wit...  
2     A scientist in a lab coat is using a microscope.  
3         A friend to everybody is a friend to nobody.  
4    A group of people, one of them with a guitar, ...  
..                                                 ...  
445          But, as time passed, Tangier had changed.  
446               This plank was made for walking on .  
447  She was beautiful from behind, but he couldn't...  
448  A bus shuttle took us from the airport to the ...  
449             It was the pure Language of the World.  

[450 rows x 2 columns]

In [ ]:
import jiwer
from whisper.normalizers import EnglishTextNormalizer

normalizer = EnglishTextNormalizer()

In [ ]:
data["hypothesis_clean"] = [normalizer(text) for text in data["hypothesis"]]
data["reference_clean"] = [normalizer(text) for text in data["reference"]]
data

hypothesis  \
0    The boy saw that every time he hit the alarm h...   
1    The faces were hidden behind blue veils with o...   
2        A scientist in the lab is using a microscope.   
3         A friend to everybody is a friend to nobody.   
4    A group of who could learn from them with a gu...   
..                                                 ...   
445           But as time passed, channel has changed.   
446                 This plan was made for working on.   
447  She was beautiful from behind but he couldn't ...   
448  Now, buzz, shadow, to pass from the airport to...   
449             It was the pure language of the world.   

                                             reference  \
0    The boy swore that, every time he heard the al...   
1    Their faces were hidden behind blue veils, wit...   
2     A scientist in a lab coat is using a microscope.   
3         A friend to everybody is a friend to nobody.   
4    A group of people, one of them with a guitar, ...   
..                                                 ...   
445          But, as time passed, Tangier had changed.   
446               This plank was made for walking on .   
447  She was beautiful from behind, but he couldn't...   
448  A bus shuttle took us from the airport to the ...   
449             It was the pure Language of the World.   

                                      hypothesis_clean  \
0    the boy saw that every time he hit the alarm h...   
1    the faces were hidden behind blue veils with o...   
2         a scientist in the lab is using a microscope   
3          a friend to everybody is a friend to nobody   
4    a group of who could learn from them with a gu...   
..                                                 ...   
445             but as time passed channel has changed   
446                  this plan was made for working on   
447  she was beautiful from behind but he could not...   
448  now buzz shadow to pass from the airport to th...   
449              it was the pure language of the world   

                                       reference_clean  
0    the boy swore that every time he heard the ala...  
1    their faces were hidden behind blue veils with...  
2      a scientist in a lab coat is using a microscope  
3          a friend to everybody is a friend to nobody  
4    a group of people one of them with a guitar we...  
..                                                 ...  
445             but as time passed tangier had changed  
446                 this plank was made for walking on  
447  she was beautiful from behind but he could not...  
448  a bus shuttle took us from the airport to the ...  
449              it was the pure language of the world  

[450 rows x 4 columns]

In [ ]:
non_english=((len(language) - language.count('en')) / len(language))
print(f"Non English ratio: {non_english * 100:.2f} %")

wer = jiwer.wer(list(data["reference_clean"]), list(data["hypothesis_clean"]))

print(f"WER: {wer * 100:.2f} %")

Non English ratio: 16.67 %
WER: 55.97 %


In [ ]:
def bleu_eval(predictions,references):
  bleu = evaluate.load("bleu")
  results = bleu.compute(predictions=predictions, references=references)
  print(results)
def rouge_eval(predictions,references):
  rouge = evaluate.load("rouge")
  results = rouge.compute(predictions=predictions, references=references)
  print(results)

In [ ]:
bleu_eval(predictions=data["hypothesis_clean"], references=data["reference_clean"])

{'bleu': 0.37011904690145675, 'precisions': [0.5494791666666666, 0.4134742404227213, 0.3235653235653236, 0.2552725280745001], 'brevity_penalty': 1.0, 'length_ratio': 1.1526206418840914, 'translation_length': 4992, 'reference_length': 4331}


In [ ]:
rouge_eval(predictions=data["hypothesis_clean"], references=data["reference_clean"])

{'rouge1': 0.6130420456033826, 'rouge2': 0.4702735140368728, 'rougeL': 0.6102166617608209, 'rougeLsum': 0.609515227595427}
